[package]
name = "edgy-style-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
proc-macro2 = "1"
embedded-graphics = "0.8.1"
simplecss = { path = "./simplecss" }
